# Generated by Django 3.0.3 on 2020-07-09 15:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200624_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Design', 'Design'), ('Photography', 'Photography'), ('Fashion', 'Fashion'), ('News', 'News'), ('Culture', 'Culture'), ('Sports', 'Sports'), ('uncategorized', 'uncategorized')], default='uncategorized', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
